project:
  type: website
  post-render:
    - "cp -rnv assets/. _site/assets/"
  resources:
    - "demos/sartori-lite/**"
website:
  title: "Concept Integration Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: "Team"
      - href: research_design.qmd
        text: "Research Design"
      - text: "Projects"
        menu:
          - text: "Ontology enrichment"
            href: ontology_enrichment.qmd
          - text: "Constitutional analysis"
            href: constitutional_analysis.qmd
          - text: "Consultation analysis"
            href: consultation_analysis.qmd
          - text: "Court analysis"
            href: court_analysis.qmd
          - text: "Concept repository"
            href: ontology_repository.qmd
      - href: collaboration.qmd
        text: "Collaboration"
        
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
