project:
  type: website

website:
  title: "Concept Integration Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: "Team"
      - href: research_design.qmd
        text: "Research Design"
      - text: "Projects"
        menu:
          - text: "Constitutions"
            icon: book
            href: constitutions.qmd
          - text: "Public consultations"
            icon: megaphone
            href: public_consultations.qmd
          - text: "Court rulings"
            icon: bank2
            href: court_rulings.qmd

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
