---
title: "Collaboration"
---

The heart of this research effort, as with all scientific pursuits, is the advancement of our collective understanding of the world. Perhaps more than our usual research efforts, though, this project is inspired by and hinges on the integration of research and ideas across research communities. Collaboration is thus a central focus of our work.

The project will hold periodic meetings of comparative law scholars and taxonomists to foster conceptual integration. The meetings will likely be hybrid meetings, with in-person and virtual participation options. We invite participants from diverse regions and fields who produce or classify data in many areas of comparative law. 

These collaborative meetings will allow participants to present datasets and accompanying ontologies, discuss best practices related to ontologies, build working relationships, and collaborate on conceptual integration. The meetings will also serve as a way to vet initial inputs into our planned [ontology repository](https://conceptintegration.github.io/ontology_repository.html).

If you have data, ontologies, or corpora in comparative law that could be a good fit, please contact [Zachary Elkins](mailto:zelkins@austin.utexas.edu), [Roy Gardner](mailto:roybowesgardner@gmail.com), and [Ashley Moran](mailto:ashleymoran@utexas.edu). We look forward to talking with you and learning about your work!
