---
title: "Constitutional Analysis"
---

Constitution drafters and researchers have long explored the origins and consequences of constitutional ideas—to learn why constitutions succeed and falter, when constitutional ideas gain traction, and how they shape people’s lives. Yet it is hard to analyze these questions across different countries and contexts without a coordinated approach to conceptualizing and identifying these ideas. CCP’s current analysis of 330 features across constitutions is a robust start at systematic analysis of national constitutions, yet an expanded set of topics and tools will allow us to identify myriad additional topics. Human-based content analysis is time-consuming, costly, and (even with rigorous coding procedures) inherently subjective. On the other hand, our NLP tools support automated content analysis that is more comprehensive, objective, and reproducible.

Our constitutional project thus uses our new CCP ontology to conduct an expanded analysis of constitutions. The aim is to produce complete section-level topic coverage of national constitutions worldwide. This will identify topics in constitution sections that are not yet indexed by CCP and will identify even more topics in those sections already indexed by CCP.

Our approach takes several steps to identify a comprehensive set of topics in national constitutions worldwide. This will:

* Use the new CCP ontology to automatically classify the topic of each section of all national constitutions currently in force around the world.
* Apply new and revised topic assignments to all current constitutions.
* Publish the new constitutional data on GitHub and on Constitute.

This allows us to answer several research questions related to constitutional analysis, including: What new topics and patterns are revealed in analyzing the full topical scope of the world’s constitutions? How can we measure improvements in new topic discovery in constitutions? How can we validate the reduction of constitutional content without a CCP topic and the accuracy of topic matching to constitutions?

## Publications

**Explaining What Is (and Isn't) in the New Chilean Draft Constitution**

This website story uses several translated Chilean draft constitutions that this project translated and tagged with topics to explain how members of the public can use CCP’s constitutional comparison tools to analyze the draft constitution before voting on it. View the [story](https://comparativeconstitutionsproject.org/exploring-what-is-and-isnt-in-the-new-chilean-draft-constitution-2/).

**12 Core Attributes of the Chilean Constitutional Proposal**

This website story uses Chilean draft constitutions translated and tagged by this project to assess key aspects of the draft constitution that went before voters in December 2023 and how it differed from prior proposals. View the [story](https://www.constituteproject.org/data-stories/chile-2023-proposal).

## Tools

**Constitution Comparison Tool**

This tool measures the semantic alignment of constitutions using two methods. First, it computes the distributions of the semantic similarities of all sections in a pair of constitutions and measures the differences between these distributions. Second, it compares the distributions of topic-section semantic similarities between two or more constitutions. We are currently using this tool in our work and preparing it for public release in the next year.

## Documentation

**Revised Tagging of Constitutions**

This documentation describes our rationale for revising CCP tagging of national constitutions. CCP has previously tagged many sections of constitutions at the title level, for example tagging an entire article on the judiciary with a judiciary topic at the article title level since most or all sub-sections in that article relate to the judiciary. While this is intelligible for people using these constitutional tags, it poses challenges for using these tags with NLP tools that require all segments tagged with a topic to provide substantive evidence of that topic. We are thus revising our topic tagging in national constitutions to bring all title-level tags down to the segment level. View our [revised tagging of constitutions](https://github.com/conceptintegration/conceptintegration.github.io/blob/main/revised_tagging.pdf).
