---
title: "Consultation Analysis"
---

Public consultation has become an indispensable part of constitutional design, yet the voluminous narrative data produced are notoriously difficult to analyze. Most recently, the consultation process in Chile produced more than 2.4 million suggestions for constitutional content and nearly 265,000 more comments explaining these. The question guiding such consultations—“Which constitutional topics are of most interest to citizens?”—is intractable without an applicable ontology and a method for analyzing vast volumes of text.

Our consultation project has developed tools to link constitutional content to public consultation input to assess the prevalence, evolution, and uptake of constitutional ideas raised by citizens. We are currently analyzing the world’s most recent and ambitious consultation effort in Chile. Detailed, systematic analysis of such voluminous public consultation input has been prohibitively complex to date, but our new tools make it possible. 

Our approach takes several steps to assess the constitutional topics raised in Chilean public consultations. This will:

* Use our CCP ontology to automatically classify the topics raised in public consultation input.
* Trace the prevalence, evolution, and uptake of citizens’ constitutional ideas across the Chilean constitutional reform process, including public consultations held before and during the constitutional drafting, deliberations in the drafting body, and the final constitutional text.
* Compare the prevalence of topics raised in Chilean public consultations to topics entrenched in the world’s constitutions.

This allows us to answer several research questions related to public consultations, namely: Which constitutional topics are raised most often in Chilean public consultations and drafting body deliberations? How do topics raised in Chile compare to those in constitutions globally? Do drafters leverage public input rhetorically or substantively in the drafting process? How does the design and timing of consultations shape constitutional text? How can we validate the accuracy of topic matching to consultation corpora?

## Publications

**Title:** Measuring Constitutional Preferences: A New Method for Analyzing Public Consultation Data

**Abstract:** Public consultation has become an indispensable part of constitutional design, yet the voluminous, narrative data produced are often impractical to analyze. There are also few, if any, standards for such analysis. Using a comprehensive reference ontology from the Comparative Constitutions Project (CCP), we develop a new methodology to identify constitutional topics of most concern to citizens and compare these to topics in constitutions globally. We analyze data from Chile’s 2016 public consultations—an ambitious process that produced nearly 265,000 narrative responses and launched the constitutional reform process that remains underway today. We leverage advances in natural language processing, in particular sentence-level semantic similarity technology, to classify consultation responses with respect to constitutional topics. Our methodology has potential for advocates, drafters, and researchers seeking to analyze public consultation data that too often go unexamined. View the [article](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0295396) and [replication data](https://doi.org/10.5281/zenodo.10206513).

## Papers

**Title:** Tracing the Expression and Uptake of Constitutional Ideas across Three Reform Efforts in Chile

**Abstract:** Constitution-making is arguably one of the most important moments for articulating a country's social and political vision. And yet, there is little comparative, empirical research tracing the development of this vision across an entire constitution-making process. Three recent constitutional reform efforts in Chile offer an unparalleled opportunity to examine the impacts of varied approaches to public consultation and constitution drafting on the expression and uptake of constitutional ideas. Prior analysis of these consultations (Fierro et al. 2017; Ureta et al. 2021; Raveau et al. 2022) and drafting processes (Escudero 2021; Piscopo and Siavelis 2021) has been notable but limited, due in part to the challenges of analyzing voluminous textual data produced by such legal processes. Natural language processing offers a systematic approach to analyzing the topics raised in such legal processes, allowing us to trace the uptake and evolution of constitutional ideas across Chile's historic constituent process.

Using a comprehensive set of constitutional topics and new concept processing tools, this paper compares topics raised in public consultations, drafting deliberations, and constitution drafts in Chile's constituent process over the last decade. To do so, we compile qualitative public input, transcribe drafting body deliberations, and process constitution drafts from all three recent drafting processes in Chile: the process conducted by then-President Michelle Bachelet from 2016-17, the Constitutional Convention process from 2021-22, and the Expert Commission and Constitutional Council process conducted in 2023. We assess which topics were of most interest to Chileans in each phase, whether drafters leveraged public input rhetorically or substantively, and whether the design of consultations and drafting bodies shaped the resulting constitutional texts. This informs our understanding of the Chilean process and gleans lessons for constitution making more broadly.
