---
title: "Court rulings"
---

Studies on judicial rulings focus largely on one country over time or on a finite set of topics in several countries. Such studies have been key to understanding the legal dynamics of that country or issue set, but they don't compare all of the issues people bring to courts across many countries. To date, it has been prohibitively complex to study court elaboration of the all constitutional topics in a large set of countries.

Our court project has developed tools to link constitutional content to court rulings to assess court elaboration of the full suite of constitutional topics. We are using these to identify the constitutional topics raised in court rulings in over 100 countries. Our approach takes several steps to:

* Use our CCP ontology to automatically classify the topics raised in court rulings in over 100 countries. 
* Trace the prevalence, evolution, and extension of constitutional ideas raised in court rulings within and across these countries.
* Compare the prevalence of topics raised in court cases to those entrenched in the world’s constitutions.

This allows us to answer several research questions related to court rulings: Which constitutional ideas are (and are not) brought before the courts? How does this vary across countries and legal systems? How does the understanding of these constitutional ideas evolve after judicial review? In Chile, were constitutional reform priorities raised by citizens also litigated in courts or only shared in consultation fora? How can we validate the accuracy of topic matching to court rulings?
