---
title: "Court Analysis"
---

Studies on court rulings focus largely on one country over time or on a finite set of topics in several countries. Such studies have been key to understanding the legal dynamics of that country or issue set, but they don't compare all of the issues people bring to courts across many countries. To date, it has been prohibitively complex to study court elaboration of all constitutional topics in a large set of countries.

Our court project has developed tools to link constitutional content to court rulings to assess court elaboration of the full suite of constitutional topics. We are using these to identify the constitutional topics raised in court rulings in over 100 countries. Our approach takes several steps to:

* Use our CCP ontology to automatically classify the topics raised in court rulings in over 100 countries. 
* Trace the prevalence, evolution, and extension of constitutional ideas raised in court rulings within and across these countries.
* Compare the prevalence of topics raised in court cases to those entrenched in the world’s constitutions.

This allows us to answer several research questions related to court rulings, including: Which constitutional ideas are (and are not) brought before the courts? How does this vary across countries and legal systems? How does the understanding of these constitutional ideas evolve after judicial review? In Chile, were constitutional reform priorities raised by citizens also litigated in courts or only shared in consultation fora? How can we validate the accuracy of topic matching to court rulings?

## Papers

**Title: Which Constitutional Ideas are Most Litigated in Courts?**

**Abstract:** Courts are central to the enforcement and elaboration of constitutions. Nearly 80% of countries today explicitly grant one or more courts the power to interpret the constitution (Elkins and Ginsburg 2022), positioning courts to shape broad swaths of the political and social realm (Stone Sweet 2000; Hirschl 2004). Yet cross-national assessment of such court elaboration has been relatively narrow. Studies of court rulings typically focus on one country over time or on a finite set of topics in several countries. Such studies have been key to understanding the legal dynamics of that country or issue set, but they do not reveal all of the constitutional issues people bring to courts around the world. To date, it has been prohibitively complex to assess the litigation of all constitutional topics in a large set of countries.

This paper presents a new approach to assessing the constitutional content of court rulings, identifying the constitutional ideas that are most litigated in courts globally. To do so, we use the Comparative Constitutions Project (CCP) vocabulary that tracks more than 330 topics in national constitutions (Elkins and Ginsburg 2022). We use new multi-lingual, semantic similarity tools to apply these topics to an extensive collection of national court rulings compiled by the European Commission for Democracy through Law (Venice Commission n.d.). This dataset includes nearly 15,000 court rulings from 120 countries in Africa, the Americas, Asia, and Europe since 1803, allowing us to identify the most litigated constitutional topics in a much broader set of courts than has been compared previously. This methodology allows us to trace constitutional content through court rulings over time and across diverse regions of the world, exploring which constitutional topics are and are not litigated in courts and how this varies across countries and legal regimes.
