---
title: "Concept Integration in Comparative Law"
---

Concepts are at the core of scientific inquiry. In some fields, systematizing and organizing concepts has been a central concern, and has even led to high levels of consensus on categories and labels. The Linnaean taxonomy in biology and the Diagnostic and Statistical Manual in Psychiatry are two well-known examples. In other fields, such as political science and law, concepts are less regulated. 

Uncoordinated proliferation of conceptual frameworks in comparative law constrains systematic comparison and alignment of findings across studies, and in turn constrains the accumulation of knowledge. Fifty years ago, Giovanni Sartori and others—concerned about just such a “Tower of Babel” problem in political science—spearheaded a movement towards a more self-conscious use of concepts. Like Sartori, we recognize the personal and collective benefits of analyzing concepts and associating them with empirical phenomena. We also perceive an opportunity to use technology to advance this work. 

Natural language processing (NLP) can accelerate a more systematic approach to the representation of concepts in comparative law. We are developing concept-processing tools that measure the semantic similarity of sentence-level text segments, with no preprocessing of text. These allow us to analyze the large volumes of text generated from legal processes like constitutional design, public consultation, and court rulings—all critically important processes with products that have historically been too unwieldy to analyze in a broadly comparative way. 

Our digital tools facilitate the systematic comparison, integration, and application of concepts across comparative law. We seek to use them to improve constitutional design by organizing and enriching the historical and cross-national information available to constitution drafters and analysts. But they are applicable across the constitutional domain and beyond.

**Funding acknowledgement:** This material is based upon work supported by the National Science Foundation under Grant Number 2315189. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the National Science Foundation (NSF). We deeply appreciate NSF's Accountable Institutions and Behavior program and Human Networks and Data Science program for this support.
