---
title: "Public Consultations"
---

Public consultation has become an indispensable part of constitutional design, yet the voluminous narrative data produced are notoriously difficult to analyze. Most recently, the consultation process in Chile produced more than 2.4 million suggestions for constitutional content and nearly 265,000 more comments explaining these. The question guiding such consultations—“Which constitutional topics are of most interest to citizens?”—is intractable without an applicable ontology and a method for analyzing vast volumes of text.

Our consultation project has developed tools to link constitutional content to public consultation input to assess the prevalence, evolution, and uptake of constitutional ideas raised by citizens. We are currently analyzing the world’s most recent and ambitious consultation effort in Chile. Detailed, systematic analysis of such voluminous public consultation input has been prohibitively complex to date, but our new tools make it possible. 

Our approach takes several steps to assess the constitutional topics raised in Chilean public consultations. This will:

* Use our CCP ontology to automatically classify the topics raised in public consultation input.
* Trace the prevalence, evolution, and uptake of citizens’ constitutional ideas across the Chilean constitutional reform process, including public consultations held before and during the constitutional drafting, deliberations in the drafting body, and the final constitutional text.
* Compare the prevalence of topics raised in Chilean public consultations to topics entrenched in the world’s constitutions.

This allows us to answer several research questions related to public consultations, namely: Which constitutional topics are raised most often in Chilean public consultations and drafting body deliberations? How do topics raised in Chile compare to those in constitutions globally? Do drafters leverage public input rhetorically or substantively in the drafting process? How does the design and timing of consultations shape constitutional text? How can we validate the accuracy of topic matching to consultation corpora?
