---
title: "Research Design"
---

We have developed a novel set of concept-processing tools that form the basis of our research design to enrich our CCP ontology and apply it to new research frontiers. Text comparison poses formidable challenges for human experts, as an exhaustive comparison of just two 1,000-topic texts requires one million operations. NLP tools can automate part of this task, calculating similarities between text at various levels—words, sentences, and documents.

## Methodology

The NLP methods we use—those within vector semantics—assess the similarity of meaning regardless of word choice and order, out-performing other NLP tools in sentence-level semantic tasks. Specifically, we use version 4 of Google’s Universal Sentence Encoder (USE) model and version 3 of the multilingual USE model to support our work in ontology enrichment and concept integration. Over the last 10 years, we have experimented with other NLP methods, but in our view, vector semantics shows the most promise.

We are using these tools to: (1) refine the Comparative Constitutions Project (CCP) ontology for use with NLP tools and integrate multiple conceptual frameworks from comparative law to provide broader topic coverage, (2) use the new CCP ontology to provide section-level topic coverage of national constitutions globally, (3) link constitutional content to public consultation input to assess the prevalence, evolution, and uptake of constitutional ideas raised by citizens, and (4) link constitutional content to court rulings to assess the prevalence, evolution, and extension of constitutional ideas brought to courts around the world.

## Research Products

Our methods translate to a series of research products we use in our own work but also intend to be useful to other researchers working in the legal domain. These include: (1) an [expanded CCP ontology](https://conceptintegration.github.io/ontology_enrichment.html), optimized for use with NLP tools and expanded to provide broader topic coverage, (2) comprehensive [constitutional analysis](https://conceptintegration.github.io/constitutional_analysis.html) of topics in national constitutions worldwide, (3) new methods for discovering and tracing ideas raised in public comments during [constitutional consultations](https://conceptintegration.github.io/consultation_analysis.html), (4) a systematic analysis of constitutional ideas raised in [court rulings](https://conceptintegration.github.io/court_analysis.html) worldwide, revealing which constitutional ideas gain traction and how they evolve after the constitution’s adoption, (5) a public [ontology repository](https://conceptintegration.github.io/ontology_repository.html) where scholars can share, explore, and integrate concepts across the field of comparative law, and (6) [interactive tools](https://conceptintegration.github.io/ontology_enrichment.html) to explore ontologies and corpora using our methodology.

## Research Contributions

We aim to make several methodological, ontological, and substantive contributions to the field of comparative law. On the methodological side, we are developing multilingual concept processing tools that compare and integrate concepts and ontologies in comparative law. On the ontological side, we are developing a replicable process for optimizing the performance of ontologies in semantic-similarity applications, refining and expanding our CCP ontology, and creating a public repository for ontologies in comparative law. On the substantive side, we are identifying geographic and temporal patterns in the constitutional ideas entrenched in constitutions, raised by citizens, and litigated in courts.
